repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files
        args: [ "--maxkb=500" ]
      - id: check-ast
      - id: check-symlinks
      - id: check-docstring-first
        exclude: "^docs\\/|^tests\\/|setup.py"
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: ".md$"
      - id: mixed-line-ending
      - id: check-yaml
      - id: check-ast
      - id: no-commit-to-branch
  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args: [--profile=black]
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        exclude: "^docs\\/|^tests\\/|setup.py"
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        exclude: "setup.py"
        args:
          [
            "-rn", # Only display messages
            "-sn", # Don't display the score
            "--rcfile=.pylintrc", # Link to your config file
            "--load-plugins=pylint.extensions.docparams", # Load an extension
          ]
