service: server

provider:
  name: aws
  runtime: python3.8

iamRoleStatements:
  - Effect: "Allow"
    Action:
      - "s3:ListBucket"
      - "s3:GetObject"
      - "s3:PutObject"
    Resource:
      Fn::Join:
        - ""
        - - "arn:aws:s3:::space-track-cache"

functions:
  hello:
    handler: handler.hello
  events:
    - http:
        path: /tle/day
        method: post

plugins:
  - serverless-python-requirements
