service: st-cache

provider:
  name: aws
  region: us-west-2
  runtime: python3.8
  stage: dev
  lambdaHashingVersion: "20201221"

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
        - "s3:GetObject"
        - "s3:PutObject"
      Resource: 
        - "arn:aws:s3:::space-track-cache/*"

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: '/tle/day'
          method: post

plugins:
  - serverless-python-requirements
  - serverless-domain-manager

custom:
  customDomain:
    domainName: "api.txcl.io"
    basePath: ''
    stage: "dev"
    createRoute53Record: true
